//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_przychodnia_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int ID_wizyty { get; set; }
        public Nullable<int> Rejestracja_ID { get; set; }
        public Nullable<int> Pracownicy_ID { get; set; }
        public Nullable<int> Pacjenci_ID { get; set; }
        public string Kod_choroby { get; set; }
        public string Diagnoza { get; set; }
    
        public virtual Pacjenci Pacjenci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rejestracja Rejestracja { get; set; }
    }
}
